### ISSUE TITLE
Feature Request: truststore location and context

### ISSUE THREAD

**Issue by oiime** [RedpointGames/pkgsign#10]
Allow specifying the location of the truststore, alternatively allow a localized truststore (within the work directory) to be distributed with the git repository for collaborators, just because I trust a package in one context doesn't mean I automatically trust it in another, I also might want to share what I trust in a certain context with other machines (deployment) and users (collaborators)

**Comment by hach-que** [comment]
I don't intend (at this time) to pursue this.

There's scenarios where someone compromises a Git repository, you pull the latest version, and suddenly you're now trusting a different person to sign a package because the trust store in that repository was modified. This opens up an attack vector (especially if the trust store can be stored in the same repository as an actual package that contributors are working on).

I think expected identities is a much better way of approaching this. After 0.2.0, you'll be able to embed expected identities in packages. This will allow you to create a metapackage on NPM with all the dependencies you want to trust, then you can sign the metapackage and (in your corporate environment), trust that metapackage. When users are prompted to trust the dependencies for the first time, they'll be able to see that the signer's identity matches the expected identity from the metapackage. So they'll have additional information in the prompt like "Package abc is untrusted, signed by @someuser (which is the identity expected by packages def, xyz, ...), do you want to trust this package?"

**Comment by oiime** [comment]
That's up to you, but ultimately it'll prevent the tool from being used with a lot of deployment processes, in a _lot_ of cases the deployment code is not being built at a specific developer's machine, this would also prevent the person in charge of the build process from deciding package trust and prevent a single developer in the team from inadvertently introducing an untrusted package. I think more flexibility should be allowed to the user, especially a common one like deciding where the software stores its files, not everything is a neat *inx ~/ environment. About metapackages, that also requires the use of private npm in the deployment processes which really limits the number of potential users

**Comment by hach-que** [comment]
If you're doing build automation, why is it not practical to copy the trust store onto whatever build machine you're using? It's a single copy command, and doesn't introduce any mechanisms that reduce the security of contributing to open source projects.

NPM metapackages don't require a private registry; they don't contain any code, just a signature and list of dependencies to pull in.

**Comment by oiime** [comment]
eg: a layout like `/var/lib/build/one_project_of_many/env` and `/var/lib/build/one_project_of_many/package`, a build machine can have multiple projects with varying security needs and configurations, often containerized with those directories mounted externally (making ~ ephemeral not useful for storing such data)

metapackages are fine but I think in a lot of cases it'll be easier to introduce into an existing process if it also allowed to simply point at a file rather than require additional repositories

**Comment by hach-que** [comment]
If you're using containers for isolation, can you not volume mount `~/.pkgsign-trust-store` to those directories?

If you're in an environment where you want to import the trust store from the repository you're building, you can explicitly copy it across with something like `cp -Rv ./trust-store/* ~/.pkgsign-trust-store/` (or the Windows equivalent) as part of your build process.

**Comment by oiime** [comment]
Then it'll 1. require the machine the layout to be centered around using *ux ~/ enviorments, messing up any procedure that intentionally tries to keep all data in a different place (storing server data under /var is the common practice)  2. require to only have one trust store for all projects (or worse, keep overwriting it assuming there is only one build at the time) or make some other convoluted setup to bypass that restriction

it's your thing, but i definitely think allowing setting where a program stores its configuration is a rudimentary thing that exists in almost every unix program
