### ISSUE TITLE
Provide custom badge

### ISSUE THREAD

**Issue by mainrs** [RedpointGames/pkgsign#14]
A custom badge would be nice so project owners that use pkgsign can show it off by adding it to the readme file.

I just found out that shields.io lets you create custom badges. Maybe something along the lines of ![pkgsign signed](https://img.shields.io/badge/pkgsign-signed-brightgreen.svg) ... ?

**Comment by hach-que** [comment]
Yeah that looks pretty good, though maybe ![pkgsign signed by @hachque](https://img.shields.io/badge/pkgsign-signed%20by%20%40hachque-brightgreen.svg) is better.

Ideally I'd like to have a badge that's actually dynamic and shows who is signing the latest package on NPM, but as far as I'm aware there's no online API that indexes files within NPM packages, so it doesn't seem practical.

**Comment by mainrs** [comment]
I actually like the signed by one! Having it even work dynamically would be cool. But as far as I know there is no such service.

**Comment by aaronjanse** [comment]
Perhaps “pkgsigned by | @hachque” (in a fancy badge image of course)?

Either way, I bet you could setup a free GCP server to serve badges and upgrade if needed (or if you feel guilty freeloading off of GCP)

**Comment by hach-que** [comment]
I've just set up a Google Cloud Function that dynamically looks up signing status of packages by downloading the tarballs and looking at `signature.json`. 

For keybase.io identities, you can use it like this:

```
![pkgsign status](https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=pkgsign&expectedIdentity=%40hachque)
```

For PGP HTTPS URLs, you can use it like this:

```
![pkgsign status](https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=react&expectedIdentity=https%3A%2F%2Freactjs.org%2Freact.asc)
```

As a demo for how it looks, here's different scenarios:

- Package has `signature.json` with matching identity: ![pkgsign status](https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=pkgsign&expectedIdentity=%40hachque)
- Package has `signature.json` with non-matching identity: ![pkgsign status](https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=pkgsign&expectedIdentity=%40nope)
- Package is unsigned: ![pkgsign status](https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=react&expectedIdentity=https%3A%2F%2Freactjs.org%2Freact.asc)

It doesn't _yet_ actually invoke pkgsign to verify that the signature is correct, since the way pkgsign is structured at the moment it's a bit hard to use against an in-memory tarball. I'll probably get real verification into it post 0.2.0.

**Comment by mainrs** [comment]
Does it only work for this package? Because I tried it with one of my smaller test libraries and it does return a 404. Maybe it's because the name contains a hyphen. I tried it with this url: https://us-central1-pkgsign.cloudfunctions.net/pkgsign-badge?name=hex%2Ddebug&expectedIdentity=%40sirwindfield

**Comment by hach-que** [comment]
Ah, I'm not encoding dashes correctly for shields.io. I'll get that fixed.

**Comment by hach-que** [comment]
That URL should be working now.
